# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fated to Die Tools 
description: > # this means to ignore newlines until "baseurl:"
  GM-side tools for the Fated to Die RPG system.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ftd-toolkit.github.io/" # the base hostname & protocol for your site
github_username:  ftd-toolkit

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman